# Generated by Django 4.2.7 on 2025-11-05 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('quantidade', models.IntegerField(default=1)),
                ('quantidade_disponivel', models.IntegerField(default=1, help_text='Quantidade ainda disponível')),
                ('condicao', models.CharField(help_text='Ex: Novo, Usado em bom estado, etc.', max_length=100)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('reservado', 'Reservado'), ('retirado', 'Retirado'), ('cancelado', 'Cancelado')], default='disponivel', max_length=15)),
                ('urgencia', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='itens_estoque/')),
                ('visualizacoes', models.IntegerField(default=0)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_estoque', to='doacoes.categoria')),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_doados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item do Estoque',
                'verbose_name_plural': 'Itens do Estoque',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='PontoColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do ponto de coleta', max_length=200)),
                ('descricao', models.TextField(help_text='Descrição do local e como funciona')),
                ('endereco', models.CharField(max_length=255)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=10)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('horario_funcionamento', models.TextField(help_text='Ex: Segunda a Sexta, 9h às 17h')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pontos_coleta/')),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos_coleta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ponto de Coleta',
                'verbose_name_plural': 'Pontos de Coleta',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoRetirada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('retirada', 'Retirada no Local'), ('entrega', 'Entrega')], default='retirada', max_length=10)),
                ('quantidade_solicitada', models.IntegerField(default=1)),
                ('endereco_entrega', models.CharField(blank=True, max_length=255)),
                ('cidade_entrega', models.CharField(blank=True, max_length=100)),
                ('estado_entrega', models.CharField(blank=True, max_length=2)),
                ('observacao_solicitante', models.TextField(blank=True, help_text='Observações do solicitante')),
                ('observacao_responsavel', models.TextField(blank=True, help_text='Resposta/observações do responsável')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('recusada', 'Recusada'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='pendente', max_length=15)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_resposta', models.DateTimeField(blank=True, null=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='doacoes.itemestoque')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_feitas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de Retirada',
                'verbose_name_plural': 'Solicitações de Retirada',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='PostComunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('tags', models.CharField(blank=True, help_text='Separadas por vírgula', max_length=200)),
                ('fixado', models.BooleanField(default=False, help_text='Post fixado no topo')),
                ('visualizacoes', models.IntegerField(default=0)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('ponto_coleta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='doacoes.pontocoleta')),
            ],
            options={
                'verbose_name': 'Post da Comunidade',
                'verbose_name_plural': 'Posts da Comunidade',
                'ordering': ['-fixado', '-data_criacao'],
            },
        ),
        migrations.AddField(
            model_name='itemestoque',
            name='ponto_coleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='doacoes.pontocoleta'),
        ),
        migrations.CreateModel(
            name='ComentarioPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='doacoes.postcomunidade')),
                ('resposta_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='doacoes.comentariopost')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['data_criacao'],
            },
        ),
    ]
